# exp setting
exp_name: 'test'
ckpt_path: null
seed: 42
debug: True
devices: [ 0 ]

# data related
load_num_workers: 0
train_data_path: [ "data_samples/nuscenes" ]
val_data_path: [ "data_samples/nuscenes" ]
max_data_num: [ 1000 ]
past_len: 21 # 0.1s
future_len: 60 # 0.1s
object_type: [ 'VEHICLE' ]#, 'PEDESTRIAN', 'CYCLIST']
line_type: [ 'lane','stop_sign','road_edge','road_line','crosswalk','speed_bump' ] #['lane','stop_sign','road_edge','road_line','crosswalk','speed_bump']
masked_attributes: [ 'z_axis, size' ] # 'z_axis, size, velocity, acceleration, heading'
trajectory_sample_interval: 1 # 0.1s
only_train_on_ego: False
center_offset_of_map: [ 30.0, 0.0 ]
use_cache: False
overwrite_cache: True
store_data_in_memory: False

# official evaluation
nuscenes_dataroot: '/mnt/nas3_rcp_enac_u0900_vita_scratch/datasets/Prediction-Dataset/nuscenes/nuscenes_root'
eval_nuscenes: False
eval_waymo: False

defaults:
  - method: autobot